In [1]:
import torch
print(torch.__version__)

2.2.1


In [2]:
print(torch.cuda.is_available())

False


In [3]:
import numpy as np
tensor_0d = torch.tensor(1) # scalar value

In [5]:
tensor_0d.shape

torch.Size([])

In [6]:
tensor_1d = torch.tensor([1,2,3]) # 1d from list like a series
tensor_1d.shape
# 1d however it shows its size

torch.Size([3])

In [7]:
tensor_2d = torch.tensor([[1,2],[3,4]])
tensor_2d.shape 

torch.Size([2, 2])

In [10]:
tensor_3d = torch.tensor([[[1,2,3],[4,5,6],[7,8,9]],[[2,3,4],[3,4,5],[5,6,7]]])
tensor_3d.shape

torch.Size([2, 3, 3])

In [11]:
tensor_3d

tensor([[[1, 2, 3],
         [4, 5, 6],
         [7, 8, 9]],

        [[2, 3, 4],
         [3, 4, 5],
         [5, 6, 7]]])

In [12]:
ary_3d = np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
tensor_3d_2 = torch.tensor(ary_3d) # copies memory
tensor_3d_3 = torch.from_numpy(ary_3d) # shares the memory


In [14]:
ary_3d[0,0,0]=-999 # i,j,k in the dimension here i can be 0,1 j,k 0,1,2
tensor_3d_2

tensor([[[1, 2],
         [3, 4]],

        [[5, 6],
         [7, 8]]])

In [15]:
tensor_3d_3

tensor([[[-999,    2],
         [   3,    4]],

        [[   5,    6],
         [   7,    8]]])

In [17]:
tensor_2d = torch.tensor([[1,2,3],[4,5,6]])
print(tensor_2d.shape)
tensor_2d


torch.Size([2, 3])


tensor([[1, 2, 3],
        [4, 5, 6]])

In [18]:
tensor_2d.reshape(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [19]:
tensor_2d.reshape(-1) # flatten 

tensor([1, 2, 3, 4, 5, 6])

In [22]:
tensor_2d.reshape(1,6)

tensor([[1, 2, 3, 4, 5, 6]])

In [23]:
tensor_2d.reshape(6,1)

tensor([[1],
        [2],
        [3],
        [4],
        [5],
        [6]])

In [24]:
tensor_2d.view(3,2)

tensor([[1, 2],
        [3, 4],
        [5, 6]])

In [25]:
tensor_2d.view(-1)

tensor([1, 2, 3, 4, 5, 6])

## diff between view and reshape
- view requieres contiguous tensor 
- reshape is flexible, copies data in memory



In [27]:
tensor_2d.matmul(tensor_2d.T)

tensor([[14, 32],
        [32, 77]])

In [28]:
tensor_2d @ tensor_2d.T # @ refers as matrix multiplication

tensor([[14, 32],
        [32, 77]])

## using torch as a computation graph

In [29]:
import torch.nn.functional as F

y = torch.tensor([1.0])  # true label
x1 = torch.tensor([1.1]) # input feature
w = torch.tensor([2.2])  # weight param
b = torch.tensor([0.0])  # bias 

model = torch.sigmoid(x1 * w + b)
loss = F.binary_cross_entropy(model,y)

print(loss)

tensor(0.0852)


In [30]:
import torch.nn.functional as F
from torch.autograd import grad

y = torch.tensor([1.0])                     # true label
x1 = torch.tensor([1.1])                    # input feature
w = torch.tensor([2.2],requires_grad=True)  # weight param
b = torch.tensor([0.0],requires_grad=True)  # bias 

model = torch.sigmoid(x1 * w + b)
loss = F.binary_cross_entropy(model,y)

print(loss)

grad_L_w = grad(loss, w, retain_graph=True)
grad_L_b = grad(loss, b, retain_graph=True)

print(grad_L_w,grad_L_b)

tensor(0.0852, grad_fn=<BinaryCrossEntropyBackward0>)
(tensor([-0.0898]),) (tensor([-0.0817]),)


In [31]:
loss.backward() # automatic calulcation of grad if required_grad=True added for the weight parameter
print(w.grad,b.grad)

tensor([-0.0898]) tensor([-0.0817])


In [ ]:
# next implement linear regression
# logistic regression
# add callback functions 
# create simple MLP
# use object notation forward and backward
# create typical training loop
# use of different optimizer vs manual runs